#include "classes.h"

ataque psychic      ("Psiquico",        90,     "Psiquico");
ataque shadowball   ("Shadow Ball",     80,     "Fantasma");
ataque flamethrower ("Flamethrower",    90,     "Fogo");
ataque hurricane    ("Hurricane",       90,     "Voador");
ataque thunderbolt  ("Thunderbolt",     90,     "Eletrico");
ataque drillpeck    ("Drill Peck",      80,     "Voador");
ataque icebeam      ("Ice Beam",        90,     "Gelo");
ataque outrage      ("Outrage",         90,     "Dragao");
ataque aurasphere   ("Aura Sphere",     80,     "Lutador");
ataque crunch       ("Crunch",          80,     "Sombrio");
ataque hydropump    ("Hydro Pump",      90,     "Agua");
ataque dragonpulse  ("Dragon Pulse",    85,     "Dragao");
ataque solarbeam    ("Solar Beam",      90,     "Grama");
ataque focusblast   ("Focus Blast",     90,     "Lutador");
ataque bodyslam     ("Body Slam",       85,     "Normal");
ataque hyperbeam    ("Hyper Beam",      90,     "Normal");
ataque surf         ("Surf",            90,     "Agua");
ataque aquatail     ("Aqua Tail",       90,     "Agua");
ataque earthquake   ("Earthquake",      90,     "Terrestre");
ataque stoneedge    ("Stone Edge",      90,     "Pedra");
ataque brickbreak   ("Brick Break",     75,     "Lutador");
ataque closecombat  ("Close Combat",    80,     "Lutador");
ataque crosschop    ("Cross Chop",      90,     "Lutador");
ataque highjumpkick ("High Jump Kick",  90,     "Lutador");
ataque blazekick    ("Blaze Kick",      85,     "Fogo");
ataque dynamicpunch ("Dynamic Punch",   90,     "Lutador");
ataque gunkshot     ("Gunk Shot",       80,     "Venenoso");
ataque sludgewave   ("Sludge Wave",     95,     "Venenoso");
ataque twister      ("Twister",         40,     "Voador");
ataque poisonfang   ("Poison Fang",     50,     "Venenoso");
ataque hyperfang    ("Hyper Fang",      80,     "Normal");
ataque quickattack  ("Quick Attack",    40,     "Normal");
ataque tackle       ("Tackle",          40,     "Normal");
ataque ember        ("Ember",           40,     "Fogo");
ataque watergun     ("Water Gun",       40,     "Agua");
ataque vinewhip     ("Vine Whip",       45,     "Grama");
ataque fireblast    ("Fire Blast",      90,     "Fogo");
ataque airslash     ("Air Slash",       75,     "Voador");
ataque irontail     ("Iron Tail",       90,     "Metal");
ataque bugbite      ("Bug Bite",        60,     "Inseto");
ataque poisonsting  ("Poison Sting",    40,     "Venenoso");
ataque wingattack   ("Wing Attack",     60,     "Voador");
ataque scratch      ("Scratch",         40,     "Normal");
ataque razorleaf    ("Razor Leaf",      55,     "Grama");
ataque seedbomb     ("Seed Bomb",       80,     "Grama");
ataque bite         ("Bite",            60,     "Sombrio");
ataque sludgebomb   ("Sludge Bomb",     90,     "Venenoso");
ataque aerialace    ("Aerial Ace",      60,     "Voador");
ataque poisonjab    ("Poison Jab",      80,     "Venenoso");
ataque darkpulse    ("Dark Pulse",      80,     "Sombrio");
ataque hornattack   ("Horn Attack",     65,     "Normal");
ataque rockslide    ("Rock Slide",      75,     "Pedra");
ataque icepunch     ("Ice Punch",       75,     "Gelo");
ataque drillrun     ("Drill Run",       80,     "Terrestre");
ataque leafblade    ("Leaf Blade",      90,     "Grama");
ataque dragonclaw   ("Dragon Claw",     80,     "Dragao");

pokemon mewtwo      ("Mewtwo",      106,    110,    90,     50,     130,    "Psiquico", psychic,        shadowball, 220);
pokemon moltres     ("Moltres",     90,     100,    90,     45,     90,     "Fogo",     flamethrower,   hurricane,  217);
pokemon zapdos      ("Zapdos",      90,     90,     85,     44,     100,    "Eletrico", thunderbolt,    drillpeck,  216);
pokemon articuno    ("Articuno",    90,     85,     90,    43,     85,     "Gelo",     icebeam,        hurricane,  215);
pokemon dragonite   ("Dragonite",   91,     100,    95,     42,     80,     "Dragao",   dragonclaw,     outrage,    218);
pokemon mew         ("Mew",         100,    100,    90,    41,     100,    "Psiquico", psychic,        aurasphere, 64);
pokemon arcanine    ("Arcanine",    90,     110,    80,     40,     95,     "Fogo",     flamethrower,   crunch,     213);
pokemon gengar      ("Gengar",      60,     110,    60,     39,     110,    "Fantasma", shadowball,     sludgebomb, 190);
pokemon gyarados    ("Gyarados",    95,     125,    79,     38,     81,     "Agua",     hydropump,      dragonpulse,214);
pokemon exegguttor  ("Exegguttor",  95,     95,     85,     37,     55,     "Grama",    psychic,        solarbeam,  212);
pokemon alakazam    ("Alakazam",    70,     130,    50,     36,     120,    "Psiquico", psychic,        focusblast, 186);
pokemon snorlax      ("Snorlax",    110,    100,    65,     35,     30,     "Normal",   bodyslam,       hyperbeam,  154);
pokemon lapras      ("Lapras",      100,    95,     80,     34,     60,     "Agua",     icebeam,        surf,       219);
pokemon jolteon     ("Jolteon",     70,     100,    60,     33,     130,    "Eletrico", thunderbolt,    shadowball, 197);
pokemon flareon     ("Flareon",     70,     100,    60,     32,     65,     "Fogo",     flamethrower,   fireblast,  198);
pokemon vaporeon    ("Vaporeon",    70,     100,    60,     31,     65,     "Agua",     hydropump,      aquatail,   196);
pokemon nidoking    ("Nidoking",    81,     98,     77,     30,     85,     "Venenoso", earthquake,     poisonjab,  195);
pokemon pidgeot     ("Pidgeot",     83,     92,     75,     29,     101,    "Voador",   aerialace,      hurricane,  172);
pokemon machamp     ("Machamp",     90,     94,     80,     28,     55,     "Lutador",  dynamicpunch,   crosschop,  193);
pokemon rhydon      ("Rhydon",      95,    90,     75,    27,     40,     "Terrestre",earthquake,     stoneedge,  204);
pokemon raichu      ("Raichu",      60,     88,     55,     26,     110,    "Eletrico", thunderbolt,    brickbreak, 122);
pokemon primeape    ("Primeape",    65,     89,     60,     25,     95,     "Lutador",  closecombat,    crosschop,  149);
pokemon dragonair   ("Dragonair",   61,     84,     65,     24,     70,     "Dragao",   dragonpulse,    aquatail,   144);
pokemon rapidash    ("Rapidash",    65,     87,     70,     23,     105,    "Fogo",     fireblast,      drillrun,   192);
pokemon victreebel  ("Victreebel",  80,     87,     65,     22,     70,     "Grama",    leafblade,      sludgebomb, 191);
pokemon muk         ("Muk",         60,    80,     75,     21,     50,     "Venenoso", gunkshot,       sludgewave, 157);
pokemon onix        ("Onix",        35,     70,     70,    20,     70,     "Pedra",    earthquake,     stoneedge,  108);
pokemon hitmonchan  ("Hitmochan",   50,     100,    53,     19,     76,     "Lutador",  closecombat,    icepunch,   140);
pokemon hitmonlee   ("Hitmonlee",   50,     100,    79,     18,     87,     "Lutador",  highjumpkick,   blazekick,  139);
pokemon machoke     ("Machoke",     80,     98,     70,     17,     45,     "Lutador",  dynamicpunch,   crosschop,  146);
pokemon golduck     ("Golduck",     80,     82,     78,     16,     85,     "Agua",     surf,           icebeam,    174);
pokemon haunter     ("Haunter",     45,     50,     45,     15,     95,     "Fantasma", shadowball,     sludgebomb, 126);
pokemon pidgeotto   ("Pidgeotto",   63,     60,     55,     14,     71,     "Voador",   aerialace,      twister,    113);
pokemon rhyhorn     ("Rhyhorn",     80,     85,     50,     13,     25,     "Terrestre",earthquake,     stoneedge,  135);
pokemon arbok       ("Arbok",       60,     85,     69,     12,     80,     "Venenoso", gunkshot,       earthquake, 147);
pokemon sandslash   ("Sandslash",   75,     70,     40,     11,     65,     "Terrestre",earthquake,     stoneedge,  163);
pokemon geodude     ("Geodude",     40,     60,     40,     10,     20,     "Pedra",    earthquake,     rockslide,  86);
pokemon nidoran     ("Nidoran",     46,     57,     40,     9,      40,     "Venenoso", poisonjab,      hornattack, 60);
pokemon ekans       ("Ekans",       35,     60,     44,     8,      55,     "Venenoso", poisonjab,      darkpulse,  62);
pokemon pikachu     ("Pikachu",     35,     60,     44,     7,      90,     "Eletrico", thunderbolt,    irontail,   82);
pokemon mankey      ("Mankey",      40,     80,     35,     6,      70,     "Lutador",  closecombat,    crosschop,  74);
pokemon caterpie    ("Caterpie",    45,     30,     35,     5,      42,     "Inseto",   bugbite,        tackle,     53);
pokemon zubat       ("Zubat",       40,     45,     35,     4,      55,     "Venenoso", wingattack,     poisonfang, 54);
pokemon rattata     ("Rattata",     30,     56,     35,     3,      72,     "Normal",   hyperfang,      quickattack,57);
pokemon pidgey      ("Pidgey",      40,     45,     40,     2,      56,     "Voador",   twister,        aerialace,  55);
pokemon weedle      ("Weedle",      40,     35,     30,     1,      50,     "Inseto",   bugbite,        poisonsting,52);
pokemon charizard   ("Charizard",   100,    200,    10000,  32,     65,     "Fogo",     fireblast,      airslash,   209);
pokemon blastoise   ("Blastoise",   79,     83,     100,    32,     78,     "Agua",     hydropump,      icebeam,    210);
pokemon venusaur    ("Venusaur",    80,     82,     83,     32,     80,     "Grama",    solarbeam,      sludgebomb, 208);
pokemon charmeleon  ("Charmeleon",  100,    200,    10000,  15,     65,     "Fogo",     flamethrower,   dragonclaw, 142);
pokemon wartortle   ("Wartortle",   59,     63,     80,     15,     58,     "Agua",     aquatail,       bite,       143);
pokemon ivysaur     ("Ivysaur",     60,     62,     63,     15,     60,     "Grama",    razorleaf,      seedbomb,   141);
pokemon charmander  ("Charmander",  100,    200,    10000,  14,     65,     "Fogo",     ember,          scratch,    65);
pokemon squirtle    ("Squirtle",    44,     48,     65,     1,      43,     "Agua",     watergun,       tackle,     66);
pokemon bulbasaur   ("Bulbasaur",   45,     49,     49,     1,      45,     "Grama",    vinewhip,       tackle,     64);